# Generated by Django 3.1.3 on 2022-07-26 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Pending', max_length=230)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100)),
                ('due', models.CharField(choices=[('Due', 'Due'), ('Overdue', 'Overdue'), ('Done', 'Done')], default='Due', max_length=100)),
                ('assign', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
            ],
            options={
                'ordering': ['project', 'task_name'],
            },
        ),
    ]
