# Generated by Django 3.1.3 on 2022-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220729_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/img/avatar/avatar.jpg', null=True, upload_to='project'),
        ),
    ]
