# Generated by Django 3.1.3 on 2022-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_project_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
