# Generated by Django 3.1.3 on 2022-08-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_project_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Pending', max_length=230),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Pending', max_length=100),
        ),
    ]
