# Generated by Django 3.1.3 on 2022-07-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/img/avatar/avatar.jpg', null=True, upload_to='profile'),
        ),
    ]
