# Generated by Django 3.1.3 on 2022-08-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_utils', '0002_notificationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='from_user',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
